### ISSUE TITLE
Problematic logic in equipping deathmatch NPC with gauntlets/gloves

### ISSUE THREAD

**Issue by actual-nh** [tnnt-devteam/tnnt#3]
https://github.com/tnnt-devteam/tnnt/blob/f5eac47c005122cef11acaf3310bc82204457ed5/src/files.c#L5174

In this and the subsequent line, **not** being of various roles is tested... with `||`, not `&&` between them. Unless a character is somehow of all of these player monster types simultaneously (or, rather, all of these player monster types are the same thing), this will never _not_ be the case.

**Comment by k21971** [comment]
Good catch. I must have been half-asleep when I made this, as the section after what you referenced is correct.

**Comment by actual-nh** [comment]
Happens to all of us...

**Comment by k21971** [comment]
Closed, see git commit bffd8b3.
